### ISSUE TITLE
ModuleNotFoundError: No module named 'textdistance'`

### ISSUE THREAD

**Issue by Siki-cloud** [eric11eca/disco#3]
Hi, I am trying to run the Disco,  but i get the below infomation: 
It appears that a file "textdistance" is missing in the 'filter' directory (distiller/filter).

Could you kindly provide it?  Many thanks~.

```
$ python run.py
Traceback (most recent call last):
  File "disco-main/run.py", line 14, in <module>
    from distiller.prompt.retrieval import get_task_class
  File "disco-main/distiller/prompt/retrieval.py", line 2, in <module>
    from distiller.prompt.lib.anli import AdversarialNliTask
  File "disco-main/distiller/prompt/lib/anli.py", line 12, in <module>
    from distiller.filter.retrieval import FILTER_DICT
  File "disco-main/distiller/filter/retrieval.py", line 3, in <module>
    from distiller.filter.core import SentencePairHeuristicFilter
  File "disco-main/distiller/filter/core.py", line 4, in <module>
    **import textdistance as tdist**
ModuleNotFoundError: No module named 'textdistance'
```

**Comment by Siki-cloud** [comment]
Sorry，i just misunderstood the error.
i had fixed it by  "pip install textdistance"😅
